---
- name: Configure SECURE server
  hosts: secure
  become: true
  roles:
    - secure

- name: Configure WAF server
  hosts: waf
  become: true
  roles:
    - waf

- name: Configure DNS server
  hosts: dns
  become: true
  roles:
    - dns
